services:
  mongo:
    image: mongo:8.2.12
    container_name: cs618-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
